eureka:
  client:
      serviceUrl:
          defaultZone: http://localhost:9993/eureka
spring:
  cloud:
      gateway:
          routes:
              - id: GestionProfesseur
                uri: lb://GestionProfesseur
                predicates:
                    - Path= /professeur/**
                filters:
                    - RewritePath= /professeur/(?<path>.*), /$\{path}

              - id: GestionCours
                uri: lb://GestionCours
                predicates:
                    - Path= /cours/**
                filters:
                    - RewritePath= /cours/(?<path>.*), /$\{path}
